import type { TitleRadarResult, TripleLineResult } from "./types";

export const DEMO_KEYWORD = "二奢";

export const DEMO_TRIPLE_LINE: TripleLineResult = {
  mode: "demo",
  graph: {
    keyword: "二奢",
    center: { id: "l0-ershe", label: "二奢", layer: "L0" },
    synonyms: ["二手奢侈品", "中古奢侈品", "二手大牌"],
    upstreamDownstream: ["腕表", "包袋", "首饰", "鉴定平台", "回收商"],
    items: [
      { id: "l1-bag", label: "包包", layer: "L1" },
      { id: "l1-watch", label: "手表", layer: "L1" },
      { id: "l1-repair", label: "修复", layer: "L1" },
      { id: "l1-recycle", label: "回收", layer: "L1" },
      { id: "l1-appraise", label: "估价", layer: "L1" },
      { id: "l1-clean", label: "洗护", layer: "L1" },
      { id: "l1-swap", label: "置换", layer: "L1" },
      { id: "l1-auth", label: "鉴定", layer: "L1" },
      { id: "l1-rolex", label: "劳力士", layer: "L1" },
      { id: "l1-jewelry", label: "首饰", layer: "L1" },
    ],
    audiences: [
      { id: "l2a-mom", label: "宝妈", layer: "L2a" },
      { id: "l2a-student", label: "学生党", layer: "L2a" },
      { id: "l2a-office", label: "上班族", layer: "L2a" },
      { id: "l2a-player", label: "奢侈品玩家", layer: "L2a" },
      { id: "l2a-friend", label: "闺蜜", layer: "L2a" },
      { id: "l2a-family", label: "家人", layer: "L2a" },
      { id: "l2a-yuan", label: "名媛", layer: "L2a" },
      { id: "l2a-qianjin", label: "千金", layer: "L2a" },
      { id: "l2a-fushao", label: "富少", layer: "L2a" },
      { id: "l2a-blogger", label: "博主", layer: "L2a" },
    ],
    motives: [
      { id: "l2b-flex", label: "装逼", layer: "L2b" },
      { id: "l2b-style", label: "穿搭", layer: "L2b" },
      { id: "l2b-deal", label: "捡漏", layer: "L2b" },
      { id: "l2b-invest", label: "投资", layer: "L2b" },
      { id: "l2b-fake", label: "假货泛滥", layer: "L2b" },
      { id: "l2b-after", label: "售后保障", layer: "L2b" },
      { id: "l2b-party", label: "聚会", layer: "L2b" },
      { id: "l2b-commute", label: "通勤", layer: "L2b" },
      { id: "l2b-value", label: "保值", layer: "L2b" },
      { id: "l2b-auth", label: "识别真假", layer: "L2b" },
    ],
  },
  questions: [
    {
      id: "q1",
      formula: "audience_item_social",
      nodes: ["闺蜜", "包包", "聚会"],
      question: "买什么样的包包在聚会上能压过闺蜜一头？",
      options: [
        "经典老花，稳妥不出错",
        "当季限定色，辨识度拉满",
        "中古稀有款，懂行的才知道",
        "小众设计师联名，话题拉满",
      ],
      hookStrength: 88,
      targetAudience: "闺蜜社交圈女性",
      contentFormat: "投票",
      cta: "估价",
    },
    {
      id: "q2",
      formula: "audience_item_motive",
      nodes: ["上班族", "包包", "通勤"],
      question: "上班通勤买什么样的包包最能搭配出高级感？",
      options: [
        "中号托特，装得下电脑还显干练",
        "链条小包，精致但容量有限",
        "尼龙轻奢，实用但少一点仪式感",
        "二手经典款，预算友好且有故事",
      ],
      hookStrength: 82,
      targetAudience: "都市上班族",
      contentFormat: "图文",
      cta: "鉴定",
    },
    {
      id: "q3",
      formula: "audience_item_value",
      nodes: ["富少", "劳力士", "保值"],
      question: "创业者想入手劳力士，买什么样的二手劳力士是最保值的？",
      options: [
        "热门运动款，流通快残值高",
        "冷门纪念款，懂的人出价高",
        "改装配件款，个性但难转手",
        "全新未佩戴，溢价但流动性一般",
      ],
      hookStrength: 90,
      targetAudience: "有预算的男性玩家",
      contentFormat: "短视频",
      cta: "估价",
    },
    {
      id: "q4",
      formula: "audience_item_motive",
      nodes: ["学生党", "包包", "识别真假"],
      question: "学生党买二奢怎么去识别真假？",
      options: [
        "只看价格是否离谱",
        "对细节图 + 查序列/钢印",
        "只信熟人代购口碑",
        "先付定金再慢慢鉴定",
      ],
      hookStrength: 92,
      targetAudience: "预算敏感学生党",
      contentFormat: "短视频",
      cta: "鉴定",
    },
    {
      id: "q5",
      formula: "pain_service_audience",
      nodes: ["假货泛滥", "鉴定", "上班族"],
      question: "假货泛滥时，上班族入手二手表最该先做哪一步？",
      options: [
        "先砍价再谈真假",
        "先验货鉴定再付款",
        "只买带原盒原证的",
        "找熟人私下交易省事",
      ],
      hookStrength: 86,
      targetAudience: "谨慎型上班族",
      contentFormat: "图文",
      cta: "鉴定",
    },
    {
      id: "q6",
      formula: "audience_item_motive",
      nodes: ["宝妈", "置换", "捡漏"],
      question: "宝妈闲置包想置换，怎样操作最不容易吃亏？",
      options: [
        "先估价再挂多个渠道比价",
        "直接低价出清省心",
        "只置换同品牌升级",
        "等节日促销再出手",
      ],
      hookStrength: 80,
      targetAudience: "宝妈闲置变现",
      contentFormat: "图文",
      cta: "置换",
    },
    {
      id: "q7",
      formula: "audience_item_social",
      nodes: ["名媛", "手表", "装逼"],
      question: "名媛局上戴哪类二手表最不容易被说「不专业」？",
      options: [
        "小表径经典石英",
        "大热钢款运动表",
        "镶钻礼服表",
        "极冷门小众品牌",
      ],
      hookStrength: 78,
      targetAudience: "社交场女性",
      contentFormat: "短视频",
      cta: "社群",
    },
    {
      id: "q8",
      formula: "audience_item_value",
      nodes: ["奢侈品玩家", "回收", "投资"],
      question: "玩家做二奢投资，回收渠道怎么选更稳？",
      options: [
        "平台一口价回收",
        "门店当面验货议价",
        "私下玩家圈子流转",
        "寄售慢慢等买家",
      ],
      hookStrength: 84,
      targetAudience: "进阶玩家",
      contentFormat: "图文",
      cta: "回收",
    },
    {
      id: "q9",
      formula: "audience_item_motive",
      nodes: ["博主", "洗护", "穿搭"],
      question: "博主要拍穿搭，二手包洗护到什么程度才出片？",
      options: [
        "深度去渍翻新",
        "轻度清洁保皮",
        "只擦五金就够",
        "保持使用痕迹更真实",
      ],
      hookStrength: 76,
      targetAudience: "内容博主",
      contentFormat: "短视频",
      cta: "私域",
    },
    {
      id: "q10",
      formula: "pain_service_audience",
      nodes: ["售后保障", "修复", "千金"],
      question: "千金的包边角磨损，修复和置换哪个更划算？",
      options: [
        "原厂级修复再继续用",
        "第三方修复够用即可",
        "直接置换升级新款",
        "先估价再决定修或换",
      ],
      hookStrength: 81,
      targetAudience: "高净值女性",
      contentFormat: "投票",
      cta: "咨询",
    },
    {
      id: "q11",
      formula: "audience_item_motive",
      nodes: ["家人", "估价", "投资"],
      question: "家人想把闲置手表当礼物转赠，先估价有必要吗？",
      options: [
        "有，避免心里落差",
        "没必要，感情大于价格",
        "只估行情不看成色",
        "直接送店里让师傅说了算",
      ],
      hookStrength: 74,
      targetAudience: "家庭决策者",
      contentFormat: "图文",
      cta: "估价",
    },
    {
      id: "q12",
      formula: "audience_item_social",
      nodes: ["学生党", "首饰", "聚会"],
      question: "学生党聚会戴二手首饰，怎样既有面又不翻车？",
      options: [
        "小牌经典款低调显质感",
        "大 logo 吸睛但易被质疑",
        "镀金仿款赌不被看穿",
        "先鉴定再晒图更安心",
      ],
      hookStrength: 85,
      targetAudience: "学生党社交",
      contentFormat: "投票",
      cta: "鉴定",
    },
  ],
};

export const DEMO_TITLE_RADAR: TitleRadarResult = {
  mode: "demo",
  referenceTitles: [
    "学生党买二奢怎么去识别真假？",
    "买什么样的包包在聚会上能压过闺蜜一头？",
    "上班通勤买什么样的包包最能搭配出高级感？",
    "创业者想入手劳力士，买什么样的二手劳力士是最保值的？",
    "假货泛滥，上班族入手二手表最该先做哪一步？",
  ],
  scores: {
    subject: 86,
    sentencePattern: 90,
    userPerception: 88,
    viewpoint: 72,
  },
  diagnosis:
    "这批标题垂直于二奢决策场景，问句与身份点名句式密度高，用户感知以避坑、社交优越和保值焦虑为主；观点表达偏「引导选择」而非强硬站队，适合投票/清单体内容放大互动。",
  patterns: [
    { label: "二奢真假避坑", kind: "题材", count: 2 },
    { label: "社交比较/压一头", kind: "题材", count: 1 },
    { label: "通勤/穿搭高级感", kind: "题材", count: 1 },
    { label: "保值投资决策", kind: "题材", count: 1 },
    { label: "身份点名 + 品类 + 问句", kind: "句式", count: 4 },
    { label: "痛点前置 + 第一步", kind: "句式", count: 1 },
    { label: "什么样的X最Y", kind: "句式", count: 3 },
  ],
  generated: [
    {
      title: "宝妈第一次买二手包，哪三个细节最容易踩假？",
      outline: [
        "开场用「收到货才发现不对」故事切入",
        "拆解五金/内衬/气味三个可执行检查点",
        "对比「便宜到不合理」与「正价二手」区间",
        "给出鉴定流程与平台选择建议",
        "CTA：评论区留「鉴定」领检查清单",
      ],
      cta: "评论区领取真假检查清单 / 私信鉴定",
    },
    {
      title: "闺蜜局上，什么价位的中古包既有面子又不显刻意？",
      outline: [
        "先定义「有面子」的社交信号",
        "给出三个价位带对应款式",
        "提醒过度 logo 的翻车风险",
        "教一招成色与搭配平衡",
      ],
      cta: "投票选出你的社交安全款",
    },
    {
      title: "上班族预算一万内，二手表怎么选才不像智商税？",
      outline: [
        "澄清预算能买到的真实区间",
        "热门款 vs 冷门款流动性对比",
        "售后与保养隐性成本",
        "给出「先鉴定再付款」行动清单",
      ],
      cta: "私域估价通道",
    },
    {
      title: "学生党捡漏二奢，怎样砍价才不会被当冤大头？",
      outline: [
        "展示常见「急出」话术陷阱",
        "用成色/配件完整性砍价模板",
        "什么时候该果断放弃",
        "成交后的鉴定兜底方案",
      ],
      cta: "关注领砍价话术卡",
    },
    {
      title: "名媛局前一夜，二手包洗护到什么程度才出片？",
      outline: [
        "镜头下最显脏的三个部位",
        "轻度清洁 vs 深度翻新成本",
        "过度翻新反而掉价的案例",
        "出门前 10 分钟快洗清单",
      ],
      cta: "预约洗护咨询",
    },
    {
      title: "富少入门劳力士，二手市场哪条「保值公式」最稳？",
      outline: [
        "保值三要素：款型、成色、流通",
        "举例两条热门与一条避坑",
        "回收残值测算方法",
        "强调正规鉴定链路",
      ],
      cta: "获取保值款短名单",
    },
    {
      title: "家人闲置包想变现，先估价还是先挂闲鱼？",
      outline: [
        "先估价避免低价甩卖",
        "多渠道比价策略",
        "照片怎么拍出价更高",
        "置换升级的适用场景",
      ],
      cta: "免费估价入口",
    },
    {
      title: "假货越来越多，博主晒二奢怎样自证不翻车？",
      outline: [
        "晒图必带的鉴定信息",
        "评论区质疑的标准回应模板",
        "商单与自用的披露边界",
        "建立长期信任的内容节奏",
      ],
      cta: "加入玩家社群",
    },
    {
      title: "通勤包选二手，怎样兼顾容量和「不像通勤包」？",
      outline: [
        "容量需求清单化",
        "外形不土的款式特征",
        "材质与季节匹配",
        "二手成色验收标准",
      ],
      cta: "领取通勤款对照表",
    },
    {
      title: "千金的包边角磨了，修复和置换到底怎么算账？",
      outline: [
        "修复报价区间与工期",
        "置换溢价/折价公式",
        "情感价值如何纳入决策",
        "给出决策树：修 / 换 / 卖",
      ],
      cta: "私信「算账」获取决策表",
    },
  ],
};
